import type { ScoreType } from "../types/scoreType";
import type { StudentType } from "../types/studentType";

export const mockScoreList: ScoreType[] = [
  {
    id: 1,
    student_id: "STU001",
    subject: "Math",
    score: 85,
    semesterSeason: "Fall",
    semesterYear: 2023,
  },
  {
    id: 2,
    student_id: "STU002",
    subject: "English",
    score: 92,
    semesterSeason: "Spring",
    semesterYear: 2024,
  },
  {
    id: 3,
    student_id: "STU003",
    subject: "Science",
    score: 78,
    semesterSeason: "Fall",
    semesterYear: 2023,
  },
  {
    id: 4,
    student_id: "STU004",
    subject: "Social Studies",
    score: 88,
    semesterSeason: "Spring",
    semesterYear: 2025,
  },
  {
    id: 5,
    student_id: "STU005",
    subject: "History",
    score: 95,
    semesterSeason: "Fall",
    semesterYear: 2024,
  },
  {
    id: 6,
    student_id: "STU006",
    subject: "English",
    score: 72,
    semesterSeason: "Spring",
    semesterYear: 2026,
  },
  {
    id: 7,
    student_id: "STU007",
    subject: "Science",
    score: 80,
    semesterSeason: "Fall",
    semesterYear: 2025,
  },
  {
    id: 8,
    student_id: "STU008",
    subject: "Math",
    score: 98,
    semesterSeason: "Spring",
    semesterYear: 2023,
  },
  {
    id: 9,
    student_id: "STU009",
    subject: "Social Studies",
    score: 75,
    semesterSeason: "Fall",
    semesterYear: 2026,
  },
  {
    id: 10,
    student_id: "STU010",
    subject: "History",
    score: 82,
    semesterSeason: "Spring",
    semesterYear: 2024,
  },
];

export const mockStudentList: StudentType[] = [
  {
    id: 1,
    avatar: "https://img.daisyui.com/images/profile/demo/distracted1@192.webp",
    student_id: "STU001",
    teacher_id: "TCHR01",
    name: "Alice Smith",
    class: "01",
    grade: "10",
    gender: "female",
  },
  {
    id: 2,
    avatar: "https://img.daisyui.com/images/profile/demo/distracted1@192.webp",
    student_id: "STU002",
    teacher_id: "TCHR02",
    name: "Bob Johnson",
    class: "02",
    grade: "11",
    gender: "male",
  },
  {
    id: 3,
    avatar: "https://img.daisyui.com/images/profile/demo/distracted1@192.webp",
    student_id: "STU003",
    teacher_id: "TCHR01",
    name: "Charlie Brown",
    class: "01",
    grade: "10",
    gender: "male",
  },
  {
    id: 4,
    avatar: "https://img.daisyui.com/images/profile/demo/distracted1@192.webp",
    student_id: "STU004",
    teacher_id: "TCHR03",
    name: "Diana Prince",
    class: "03",
    grade: "12",
    gender: "female",
  },
  {
    id: 5,
    avatar: "https://img.daisyui.com/images/profile/demo/distracted1@192.webp",
    student_id: "STU005",
    teacher_id: "TCHR02",
    name: "Eve Adams",
    class: "02",
    grade: "11",
    gender: "female",
  },
  {
    id: 6,
    avatar: "https://img.daisyui.com/images/profile/demo/distracted1@192.webp",
    student_id: "STU006",
    teacher_id: "TCHR04",
    name: "Frank White",
    class: "04",
    grade: "10",
    gender: "male",
  },
  {
    id: 7,
    avatar: "https://img.daisyui.com/images/profile/demo/distracted1@192.webp",
    student_id: "STU007",
    teacher_id: "TCHR03",
    name: "Grace Lee",
    class: "03",
    grade: "12",
    gender: "female",
  },
  {
    id: 8,
    avatar: "https://img.daisyui.com/images/profile/demo/distracted1@192.webp",
    student_id: "STU008",
    teacher_id: "TCHR01",
    name: "Henry Wilson",
    class: "01",
    grade: "10",
    gender: "male",
  },
  {
    id: 9,
    avatar: "https://img.daisyui.com/images/profile/demo/distracted1@192.webp",
    student_id: "STU009",
    teacher_id: "TCHR04",
    name: "Ivy Green",
    class: "04",
    grade: "11",
    gender: "female",
  },
  {
    id: 10,
    avatar: "https://img.daisyui.com/images/profile/demo/distracted1@192.webp",
    student_id: "STU010",
    teacher_id: "TCHR02",
    name: "Jack Taylor",
    class: "02",
    grade: "11",
    gender: "male",
  },
];
